-- Frozen predecessor catalog for the drained v22 -> v26 migration test.
-- Copied from hermes_state_pg.py at fork commit 2c3c480648fc0455c2ef6948f5d5451e38f83c12.
-- Keep this independent of the current adapter so the migration test cannot
-- manufacture its source schema by reversing the destination schema.

-- hermes-v22-statement
CREATE SCHEMA IF NOT EXISTS hermes_state

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.schema_version (
    version BIGINT NOT NULL
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.sessions (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    user_id TEXT,
    session_key TEXT,
    chat_id TEXT,
    chat_type TEXT,
    thread_id TEXT,
    display_name TEXT,
    origin_json TEXT,
    expiry_finalized BIGINT DEFAULT 0,
    model TEXT,
    model_config TEXT,
    system_prompt TEXT,
    parent_session_id TEXT,
    started_at DOUBLE PRECISION NOT NULL,
    ended_at DOUBLE PRECISION,
    end_reason TEXT,
    message_count BIGINT DEFAULT 0,
    tool_call_count BIGINT DEFAULT 0,
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    cache_read_tokens BIGINT DEFAULT 0,
    cache_write_tokens BIGINT DEFAULT 0,
    reasoning_tokens BIGINT DEFAULT 0,
    cwd TEXT,
    git_branch TEXT,
    git_repo_root TEXT,
    billing_provider TEXT,
    billing_base_url TEXT,
    billing_mode TEXT,
    estimated_cost_usd DOUBLE PRECISION,
    actual_cost_usd DOUBLE PRECISION,
    cost_status TEXT,
    cost_source TEXT,
    pricing_version TEXT,
    title TEXT,
    api_call_count BIGINT DEFAULT 0,
    handoff_state TEXT,
    handoff_platform TEXT,
    handoff_error TEXT,
    compression_failure_cooldown_until DOUBLE PRECISION,
    compression_failure_error TEXT,
    compression_fallback_streak BIGINT NOT NULL DEFAULT 0,
    profile_name TEXT,
    rewind_count BIGINT NOT NULL DEFAULT 0,
    archived BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (parent_session_id) REFERENCES hermes_state.sessions(id)
        DEFERRABLE INITIALLY IMMEDIATE
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES hermes_state.sessions(id)
        DEFERRABLE INITIALLY IMMEDIATE,
    role TEXT NOT NULL,
    content TEXT,
    tool_call_id TEXT,
    tool_calls TEXT,
    tool_name TEXT,
    effect_disposition TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    token_count BIGINT,
    finish_reason TEXT,
    reasoning TEXT,
    reasoning_content TEXT,
    reasoning_details TEXT,
    codex_reasoning_items TEXT,
    codex_message_items TEXT,
    platform_message_id TEXT,
    observed BIGINT DEFAULT 0,
    active BIGINT NOT NULL DEFAULT 1,
    compacted BIGINT NOT NULL DEFAULT 0,
    api_content TEXT
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.session_model_usage (
    session_id TEXT NOT NULL REFERENCES hermes_state.sessions(id)
        ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    model TEXT NOT NULL,
    billing_provider TEXT NOT NULL DEFAULT '',
    billing_base_url TEXT NOT NULL DEFAULT '',
    billing_mode TEXT NOT NULL DEFAULT '',
    task TEXT NOT NULL DEFAULT '',
    api_call_count BIGINT NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    actual_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_status TEXT,
    cost_source TEXT,
    first_seen DOUBLE PRECISION,
    last_seen DOUBLE PRECISION,
    PRIMARY KEY (
        session_id, model, billing_provider, billing_base_url,
        billing_mode, task
    )
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.async_delegations (
    delegation_id TEXT PRIMARY KEY,
    origin_session TEXT NOT NULL,
    origin_ui_session_id TEXT NOT NULL DEFAULT '',
    parent_session_id TEXT,
    state TEXT NOT NULL,
    dispatched_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION NOT NULL,
    event_json TEXT,
    result_json TEXT,
    delivery_state TEXT NOT NULL DEFAULT 'pending',
    delivery_attempts BIGINT NOT NULL DEFAULT 0,
    delivered_at DOUBLE PRECISION,
    owner_pid BIGINT,
    owner_started_at BIGINT,
    task_json TEXT,
    delivery_claim TEXT,
    delivery_claimed_at DOUBLE PRECISION,
    owner_instance TEXT
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.state_meta (
    key TEXT PRIMARY KEY,
    value TEXT
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.gateway_routing (
    scope TEXT NOT NULL DEFAULT '',
    session_key TEXT NOT NULL,
    entry_json TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (scope, session_key)
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.compression_locks (
    session_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.telegram_dm_topic_mode (
    chat_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    enabled BIGINT NOT NULL DEFAULT 1,
    activated_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    has_topics_enabled BIGINT,
    allows_users_to_create_topics BIGINT,
    capability_checked_at DOUBLE PRECISION,
    intro_message_id TEXT,
    pinned_message_id TEXT
)

-- hermes-v22-statement
CREATE TABLE IF NOT EXISTS hermes_state.telegram_dm_topic_bindings (
    chat_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    session_key TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES hermes_state.sessions(id)
        ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
    managed_mode TEXT NOT NULL DEFAULT 'auto',
    linked_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (chat_id, thread_id)
)

-- hermes-v22-statement
CREATE UNIQUE INDEX IF NOT EXISTS idx_telegram_dm_topic_bindings_session
ON hermes_state.telegram_dm_topic_bindings(session_id)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_telegram_dm_topic_bindings_user
ON hermes_state.telegram_dm_topic_bindings(user_id, chat_id)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_source
ON hermes_state.sessions(source)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_source_id
ON hermes_state.sessions(source, id)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_parent
ON hermes_state.sessions(parent_session_id)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_started
ON hermes_state.sessions(started_at DESC)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_messages_session
ON hermes_state.messages(session_id, timestamp)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_compression_locks_expires
ON hermes_state.compression_locks(expires_at)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_session_model_usage_session
ON hermes_state.session_model_usage(session_id)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_session_model_usage_model
ON hermes_state.session_model_usage(model)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_async_delegations_delivery
ON hermes_state.async_delegations(delivery_state, completed_at)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_messages_session_active
ON hermes_state.messages(session_id, active, timestamp)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_messages_active_null
ON hermes_state.messages(active) WHERE active IS NULL

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_session_key
ON hermes_state.sessions(session_key, started_at DESC)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_gateway_peer
ON hermes_state.sessions(
    source, user_id, chat_id, chat_type, thread_id, started_at DESC
)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_sessions_handoff_state
ON hermes_state.sessions(handoff_state, started_at)

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_messages_platform_msg_id
ON hermes_state.messages(session_id, platform_message_id)
WHERE platform_message_id IS NOT NULL

-- hermes-v22-statement
CREATE INDEX IF NOT EXISTS idx_messages_search_tsv
ON hermes_state.messages USING GIN (
    to_tsvector(
        'simple',
        left(
            COALESCE(content, '') || ' ' || COALESCE(tool_name, '') || ' '
            || COALESCE(tool_calls, ''),
            500000
        )
    )
)
